import Footer from "@/components/layout/Footer";
import MyNavbar from '@/components/layout/MyNavbar';
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"], // pick the weights you need
  display: "swap",
});

export const metadata: Metadata = {
  title: "Untitled Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <MyNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
